---
abstract: "Install all the modules from PJF's talk at OSDC 2012"
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-OSDC2012
requires:
  App::cpanminus: 0
  Dancer: 0
  Dist::Zilla: 0
  Moose: 0
  MooseX::Declare: 0
  MooseX::Method::Signatures: 0
  Perl::Critic: 0
  Plack: 0
  Regexp::Debugger: 0
  autodie: 0
  local::lib: 0
  perl: 5.010
version: 0.001
